version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel_net
    depends_on:
      - mysql
      - redis

  nginx:
    image: docker.io/library/nginx:latest
    container_name: laravel_nginx
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_net
    depends_on:
      - app

  mysql:
    image: docker.io/library/mysql:8.0
    container_name: laravel_mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel_net

  redis:
    image: redis:alpine
    container_name: laravel_redis
    networks:
      - laravel_net

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  laravel_net:
    driver: bridge
