apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  labels:
    app: laravel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-2.amazonaws.com/laravel-app:latest
        ports:
        - containerPort: 9000
        env:
        - name: APP_ENV
          value: "production"
        # - name: DB_HOST
        #   value: "<AWS_RDS_ENDPOINT>"
        # - name: REDIS_HOST
        #   value: "<AWS_ELASTICACHE_ENDPOINT>"
        volumeMounts:
        - mountPath: /var/www/html/storage
          name: storage-volume
      volumes:
      - name: storage-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9000
  selector:
    app: laravel