name: Deploy Laravel to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login/Authenticate to AWS ECR
      run: |
        aws ecr get-login-password | podman login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

    - name: Build and Push Docker Image
      run: |
        podman build -t laravel-app .
        podman tag laravel-app:latest ${{ secrets.ECR_REPOSITORY }}/laravel-app:latest
        podman push ${{ secrets.ECR_REPOSITORY }}/laravel-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Kubernetes with ArgoCD
      run: |
        kubectl apply -f k8s/laravel-deployment.yaml